name: Build LaTeX document
# Only trigger, when the build workflow succeeded

on:
  push: 
    paths: 
      - "resume/**"
      - resume.tex
      - custom-commands.tex
      - .github/workflows/resume.yml
  pull_request:
    paths: 
      - "resume/**"
      - resume.tex
      - custom-commands.tex
      - .github/workflows/resume.yml

jobs:
  Build_LaTeX_Resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile Resume
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: Commit Resume
        run: |
          mv resume.pdf public/jason-vu-resume.pdf
          git config --global user.name "javab3ans/portfolio"
          git config --global user.email "jvu@scu.edu"
          git add .
          git commit -m "📄🔨 Generate Resume" || echo
          git push
